SELECT *
FROM (
    SELECT cho.id_contract, o.name AS opcode, cho.Qntd
    FROM main.contracts_have_opcodes cho
    JOIN main.opcodes o ON o.id = cho.id_opcodes
    ORDER BY cho.id_contract
)
PIVOT (
    SUM(Qntd) FOR opcode IN (
        'ADD', 'ADDMOD', 'ADDRESS', 'AND', 'BALANCE', 'BASEFEE', 'BLOCKHASH', 'BYTE', 'CALL', 'CALLCODE',
		'CALLDATACOPY', 'CALLDATALOAD', 'CALLDATASIZE', 'CHAINID', 'CODECOPY', 'CODESIZE', 'COINBASE', 'CREATE',
		'CREATE2', 'DELEGATECALL', 'DIFFICULTY', 'DIV', 'DUP1', 'DUP10', 'DUP11', 'DUP12', 'DUP13', 'DUP14',
		'DUP15', 'DUP16', 'DUP2', 'DUP3', 'DUP4', 'DUP5', 'DUP6', 'DUP7', 'DUP8', 'DUP9', 'EQ', 'EXP',
		'EXTCODECOPY', 'EXTCODEHASH', 'EXTCODESIZE', 'GAS', 'GASLIMIT', 'GASPRICE', 'GT', 'INVALID', 'ISZERO',
		'JUMP', 'JUMPI', 'JUMPDEST', 'LOG0', 'LOG1', 'LOG2', 'LOG3', 'LOG4', 'LT', 'MLOAD', 'MOD', 'MSTORE',
		'MSTORE8', 'MSIZE', 'MUL', 'MULMOD', 'NOT', 'NUMBER', 'OR', 'ORIGIN', 'PC', 'POP', 'PUSH1', 'PUSH10',
		'PUSH11', 'PUSH12', 'PUSH13', 'PUSH14', 'PUSH15', 'PUSH16', 'PUSH17', 'PUSH18', 'PUSH19', 'PUSH2',
		'PUSH20', 'PUSH21', 'PUSH22', 'PUSH23', 'PUSH24', 'PUSH25', 'PUSH26', 'PUSH27', 'PUSH28', 'PUSH29',
		'PUSH3', 'PUSH30', 'PUSH31', 'PUSH32', 'PUSH4', 'PUSH5', 'PUSH6', 'PUSH7', 'PUSH8', 'PUSH9', 'RETURN',
		'REVERT', 'SLOAD', 'SSTORE', 'SELFBALANCE', 'SELFDESTRUCT', 'SHA3', 'SHL', 'SHR', 'SIGNEXTEND',
		'SIZE', 'SDIV', 'SGT', 'SLT', 'SMOD', 'STATICCALL', 'STOP', 'SUB', 'SWAP1', 'SWAP10', 'SWAP11',
		'SWAP12', 'SWAP13', 'SWAP14', 'SWAP15', 'SWAP16', 'SWAP2', 'SWAP3', 'SWAP4', 'SWAP5', 'SWAP6',
		'SWAP7', 'SWAP8', 'SWAP9', 'TIMESTAMP', 'XOR'
    )
);


